defaults:
    - exp: HalfCheetah-v2

demo: False  # Just run evaluation, not training.

eval:
  n_runs: 10  # Number of episodes run for each evaluation.
  interval: 20_000  # Interval (in time steps) between evaluations.

gpu: -1  # No GPU if -1.

log:
  dir: results  # Base logging directory.
  interval: 1_000  # Interval (in time steps) between outputting log messages during training
  level: 20  # Logging level.
  monitor: False  # Wrap env with gym.wrappers.Monitor.
  render: False  # Render env states in a GUI window.

pretrained:
  dir: False # Directory to load an agent from.
  load: False  # If True, a pretrained model is downloaded and used.
  type: best  # best or final.

hydra:
  run:
    dir: ./${log.dir}/mpo2/${env}/seed-${seed}/${now:%Y%m%d-%H-%M-%S}